[build]
builder = "dockerfile"

[deploy]
startCommand = "python src/webhook_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[deploy.variables]]
name = "PORT"
value = "8000"